//! Writes `GEOMETRY_QUANTUM_PER_PX` into `geometry-const.ts` alongside the
//! ts-rs-derived wire types (ts-rs has no notion of a `const`). Honours the same
//! `TS_RS_EXPORT_DIR` env var ts-rs uses (default `bindings/`). Gated on `ts-gen`
//! so it never runs in the default test gate (no IO there).

#![cfg(feature = "ts-gen")]

use std::path::PathBuf;

use shape_scene_core::object::GEOMETRY_QUANTUM_PER_PX;

#[test]
fn export_geometry_const() {
    let dir = std::env::var("TS_RS_EXPORT_DIR").unwrap_or_else(|_| "bindings".to_string());
    let mut path = PathBuf::from(dir);
    std::fs::create_dir_all(&path).expect("create export dir");
    path.push("geometry-const.ts");
    let body = format!(
        "// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). \
         Do not edit this file manually.\n\n\
         /** Quantized units per logical pixel (mirrors scene-core `GEOMETRY_QUANTUM_PER_PX`). */\n\
         export const GEOMETRY_QUANTUM_PER_PX = {GEOMETRY_QUANTUM_PER_PX};\n"
    );
    std::fs::write(&path, body).expect("write geometry-const.ts");
}
